-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1
-- Время создания: Июл 11 2019 г., 15:50
-- Версия сервера: 10.3.16-MariaDB
-- Версия PHP: 7.3.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `newsfeed`
--

-- --------------------------------------------------------

--
-- Структура таблицы `articles`
--

CREATE TABLE `articles` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `desc` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `news_users_id` bigint(20) UNSIGNED DEFAULT NULL,
  `date_created` datetime NOT NULL DEFAULT '2019-07-11 00:32:16',
  `photo` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Дамп данных таблицы `articles`
--

INSERT INTO `articles` (`id`, `title`, `desc`, `content`, `news_users_id`, `date_created`, `photo`, `created_at`, `updated_at`) VALUES
(1, 'Neque porro quisquam', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur venenatis ullamcorper augue et iaculis.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur venenatis ullamcorper augue et iaculis. Nulla pellentesque odio nec augue fermentum maximus. Mauris eget enim vel purus viverra tristique ac ut tortor. Vestibulum vitae augue a arcu blandit condimentum. Maecenas metus ligula, auctor ut tincidunt quis, dapibus eget turpis. Sed lacinia finibus mi id faucibus. Suspendisse lobortis at massa at ullamcorper. Pellentesque vestibulum volutpat laoreet. Nunc sagittis nisi vitae augue volutpat, non suscipit urna mattis. Phasellus eu dui mattis, semper ex id, tristique velit. Vestibulum dapibus sed magna quis mollis. Sed quis metus leo. Nullam maximus quam id lectus venenatis porta. In hac habitasse platea dictumst.  Duis quis laoreet metus. Nullam vel dui eros. Quisque vel auctor nisl. Nunc ex eros, mollis a malesuada quis, cursus et justo. Phasellus scelerisque imperdiet urna, quis volutpat tortor ornare vel. Vestibulum quis mauris pellentesque, egestas orci ut, dapibus mauris. Praesent euismod justo eget urna luctus, id eleifend erat scelerisque. In hac habitasse platea dictumst.', 1, '2019-07-11 02:16:37', 'preview1', NULL, NULL),
(2, 'Nullam in orci ultrices', 'Nullam in orci ultrices, dapibus massa vel, eleifend nisi. Pellentesque mollis commodo quam sit amet accumsan. Integer convallis id mauris placerat faucibus.', 'Nullam in orci ultrices, dapibus massa vel, eleifend nisi. Pellentesque mollis commodo quam sit amet accumsan. Integer convallis id mauris placerat faucibus. Nullam non posuere urna, id dapibus libero. Cras eu turpis consequat, tincidunt elit a, sodales magna. Suspendisse potenti. Proin fringilla augue ipsum, eget facilisis turpis consectetur at. In et vulputate nunc. Etiam hendrerit mauris sit amet ex elementum venenatis. Nam consectetur commodo pretium. Nullam ut diam egestas, scelerisque ligula ac, consectetur nunc.  Donec augue libero, fringilla vitae sem vitae, tincidunt porttitor magna. Fusce ante turpis, molestie auctor tellus et, suscipit malesuada justo. Nam urna orci, efficitur id dui non, imperdiet blandit lacus. Curabitur tempus blandit aliquet. Praesent rutrum nibh ut libero tristique fermentum. Aliquam vel lectus sed libero lacinia vehicula eget ut nibh. Nullam mi metus, euismod at nunc et, auctor laoreet massa. Phasellus dapibus aliquam diam id sagittis. Nam pharetra a sem at elementum. Donec porta enim quis odio gravida, ut commodo tortor tempor. Aenean commodo rutrum nisi nec fringilla. Proin euismod consectetur dui id venenatis. Fusce lorem nibh, rhoncus sit amet convallis in, hendrerit sollicitudin turpis. Curabitur malesuada nisl sit amet dolor porta condimentum.', 2, '2019-07-11 02:17:53', 'preview1', NULL, NULL),
(3, 'Nunc commodo turpis', 'Nunc commodo turpis id leo commodo porta nec eu dolor. Fusce fermentum ornare tellus in malesuada. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Nunc commodo turpis id leo commodo porta nec eu dolor. Fusce fermentum ornare tellus in malesuada. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla volutpat ornare tellus sit amet ullamcorper. Nullam consectetur mi ligula. Vestibulum pellentesque odio quis volutpat hendrerit. Nunc lectus augue, pellentesque vel arcu vitae, posuere volutpat lacus.  In eget porta arcu, id euismod velit. Pellentesque sed orci sit amet leo porta egestas. Nulla facilisi. Ut mattis sapien ut nisl pretium, eu bibendum metus fringilla. Integer sodales rutrum est a molestie. Mauris magna sem, vehicula eu sem fringilla, molestie cursus libero. Nam mollis arcu at malesuada eleifend. Mauris accumsan sed quam ut posuere. Suspendisse pellentesque ipsum ut enim pulvinar hendrerit. Donec ultricies ligula nec aliquam blandit. Phasellus sed nisi et sem placerat ultricies. Phasellus vitae magna dictum velit auctor egestas eget id massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eu lacus in erat maximus fermentum ut id mauris. Nulla ac volutpat justo, vitae mollis ipsum.', 2, '2019-07-11 02:18:32', 'preview1', NULL, NULL),
(4, 'Aliquam quis elementum enim', 'Aliquam quis elementum enim. Phasellus consectetur pulvinar cursus. Aenean congue dui sit amet ipsum tempor aliquet a ac ipsum.', 'Aliquam quis elementum enim. Phasellus consectetur pulvinar cursus. Aenean congue dui sit amet ipsum tempor aliquet a ac ipsum. Donec egestas maximus semper. Suspendisse tempor, velit ut pharetra varius, libero nibh fermentum diam, nec varius ex lectus sit amet sapien. Suspendisse vel arcu feugiat, auctor nulla non, ornare velit. Quisque eu orci tortor. Praesent vel ultricies ipsum. Morbi bibendum feugiat nulla, rhoncus efficitur lacus vulputate in. Duis id dolor blandit, elementum nunc at, dignissim metus. Nulla ligula dolor, tincidunt at lobortis eu, efficitur eget nulla. Cras ut mauris id magna sodales gravida. Cras congue arcu eu ipsum scelerisque, sit amet ornare tortor porta. Nam id scelerisque metus. In efficitur ipsum massa, nec consectetur odio vulputate a. Praesent placerat a urna egestas malesuada.  Ut magna nulla, suscipit maximus pretium et, faucibus ac quam. Sed suscipit rutrum est, vel aliquam quam dictum quis. Sed ac nunc arcu. Donec cursus pellentesque magna, ut ultricies tortor euismod ac. Proin varius justo quam. Aliquam purus sem, varius ut porta vitae, porta at diam. Donec sit amet purus a sapien mattis facilisis at ac sapien. Praesent lacus lacus, mollis non ullamcorper in, molestie non massa. Curabitur in ligula urna. Donec ultricies ut lectus in consectetur. Duis lacinia erat ullamcorper, dapibus neque in, venenatis lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor suscipit ligula in vulputate.', 1, '2019-07-11 02:19:09', 'preview1', NULL, NULL),
(5, 'Orci varius natoque penatibus', 'Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque ultricies turpis eu nulla pharetra hendrerit.', 'Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque ultricies turpis eu nulla pharetra hendrerit. Curabitur quis nulla diam. Aliquam iaculis ut urna ac tempus. Curabitur semper tincidunt ultricies. Sed lorem enim, pharetra lacinia velit sed, placerat rhoncus nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi dignissim odio elit, nec volutpat nunc elementum vitae. Vestibulum in justo ut ipsum ultricies interdum. Integer sollicitudin erat aliquet, ornare magna nec, accumsan ipsum. Cras gravida lectus sit amet metus condimentum imperdiet. Vivamus elit neque, varius eu ligula id, ultrices euismod metus. Etiam augue risus, sollicitudin non dolor iaculis, blandit tempor mi. Donec iaculis lorem non purus maximus, vel vehicula diam vestibulum. Vestibulum aliquam leo ac justo molestie vulputate. Cras aliquet magna vitae nulla pellentesque faucibus.  In ullamcorper orci sed aliquet ornare. Pellentesque condimentum ac est at facilisis. Suspendisse potenti. Integer accumsan maximus volutpat. Praesent vel nisl eget leo iaculis consectetur in sed risus. Ut feugiat cursus tellus eget scelerisque. Curabitur ut fringilla metus. Duis at leo odio. Nulla efficitur quam ligula, a posuere orci volutpat id. Mauris posuere efficitur turpis sed volutpat. Suspendisse et fringilla enim. Etiam sit amet sodales ligula, eget sodales leo. Pellentesque fringilla ac nibh eu ultrices. Suspendisse id fringilla sapien. Nullam ornare, eros in venenatis euismod, sem eros finibus ante, sed venenatis sem nisl in lorem. In hac habitasse platea dictumst.', 1, '2019-07-11 02:19:42', 'preview1', NULL, NULL),
(6, 'Donec euismod arcu gravida', 'Donec euismod arcu gravida, rhoncus nunc eu, elementum sem. Integer commodo neque elit, nec tristique velit suscipit porta.', 'Donec euismod arcu gravida, rhoncus nunc eu, elementum sem. Integer commodo neque elit, nec tristique velit suscipit porta. Nullam feugiat, justo vel rhoncus tristique, nibh dolor mollis ligula, ut auctor urna mi nec leo. Fusce vitae mi in leo ullamcorper faucibus in vestibulum risus. Vivamus ultrices vulputate consectetur. Aenean pharetra massa at mi scelerisque, sit amet pharetra orci faucibus. Fusce vitae augue vel tellus porttitor condimentum ut feugiat lorem.  Vivamus non neque rhoncus, efficitur ligula id, tempus felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc egestas dui id dignissim facilisis. Etiam vel dui vitae massa interdum tincidunt. Curabitur vehicula ante a posuere sollicitudin. Pellentesque eu dolor ac nisi lacinia aliquam. Vestibulum blandit ipsum eu pretium vestibulum. Aenean eu tortor in massa tristique lobortis. Sed nec dui sagittis, porttitor eros at, dignissim ex. Aliquam pulvinar lorem enim, ac malesuada erat ultricies vitae. Fusce ullamcorper ex at justo bibendum, et finibus diam condimentum.', 1, '2019-07-11 02:20:15', 'preview1', NULL, NULL),
(7, 'Donec viverra auctor lorem nec mollis', 'Donec viverra auctor lorem nec mollis. Nulla et ex egestas, hendrerit tellus vitae, pulvinar nulla.', 'Donec viverra auctor lorem nec mollis. Nulla et ex egestas, hendrerit tellus vitae, pulvinar nulla. Curabitur ac euismod risus. Vestibulum blandit eros et velit malesuada, at tempus odio laoreet. Donec hendrerit, est eu mattis auctor, eros metus lacinia turpis, vitae semper nibh est eu quam. Fusce maximus turpis ac sollicitudin vulputate. Fusce at enim lorem. Ut quis pellentesque ipsum. Vivamus non mi id lectus iaculis fringilla nec vel lacus. Sed placerat hendrerit risus non mollis. Quisque elementum velit sit amet purus vehicula, quis tristique eros dignissim. Donec rutrum tellus a accumsan ornare. Morbi feugiat orci in nulla faucibus consectetur. Duis quis sem sed eros feugiat tincidunt. Nunc non metus semper, venenatis odio nec, semper magna.  Duis orci risus, blandit eget fringilla non, pellentesque id risus. Donec iaculis laoreet quam at faucibus. Duis sed ultricies nunc, quis sodales tellus. Curabitur leo magna, rhoncus non enim ac, tempus eleifend leo. Proin eget mollis massa. Praesent eleifend, neque vel bibendum molestie, leo augue dapibus dui, id mollis sapien arcu in nisi. Aliquam convallis commodo nunc, mollis congue libero condimentum ac. Nunc vitae mauris justo.', 2, '2019-07-11 02:20:41', 'preview1', NULL, NULL),
(8, 'Praesent et odio a eros', 'Praesent et odio a eros sagittis venenatis feugiat quis lectus. Nam sodales eu ligula ut viverra. Duis laoreet tellus nec ex posuere, eget condimentum augue aliquet.', 'Praesent et odio a eros sagittis venenatis feugiat quis lectus. Nam sodales eu ligula ut viverra. Duis laoreet tellus nec ex posuere, eget condimentum augue aliquet. Pellentesque tempor arcu vitae malesuada sodales. Nunc faucibus aliquam sagittis. Mauris finibus orci mi, eu porttitor erat rutrum non. Pellentesque a ante egestas, venenatis metus sollicitudin, pulvinar velit. Praesent imperdiet massa mi, id sollicitudin leo rhoncus a. Sed ut justo elementum, efficitur elit nec, suscipit risus. Aenean ut finibus justo.  Integer sed vestibulum mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet velit velit, id dignissim tortor mollis id. Etiam pharetra urna et viverra facilisis. In sed leo id justo lobortis dapibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras quis nunc porttitor, elementum dui at, viverra nisi. Nunc ornare ipsum in dapibus ornare. Donec pretium augue nec erat rutrum, suscipit iaculis dui hendrerit. Nullam tincidunt, odio id convallis accumsan, velit enim tristique ligula, at gravida lorem enim sed ex. Aliquam turpis neque, mollis eget pretium vitae, porttitor quis odio.', 2, '2019-07-11 02:21:27', 'preview1', NULL, NULL),
(9, 'Nulla feugiat aliquam lacinia', 'Nulla feugiat aliquam lacinia. Sed a semper libero. Suspendisse aliquam eget mi non luctus. Nullam vestibulum enim tempus mollis venenatis.', 'Nulla feugiat aliquam lacinia. Sed a semper libero. Suspendisse aliquam eget mi non luctus. Nullam vestibulum enim tempus mollis venenatis. Quisque in luctus erat. Vestibulum sit amet turpis non leo porta interdum ac vel tellus. Curabitur sodales ultricies turpis, at interdum arcu sodales in.  Donec vitae quam leo. Ut placerat elit eget volutpat egestas. Nulla facilisi. Quisque gravida sodales cursus. Nulla convallis convallis purus, et dapibus neque. Aliquam quis neque nibh. Praesent ornare, mi ut malesuada venenatis, ante arcu gravida metus, in finibus nibh augue sed risus. Mauris eu magna ullamcorper, convallis quam ut, molestie ipsum. Donec fermentum ipsum lectus, nec finibus lacus aliquam et.  Mauris risus ipsum, vestibulum vitae semper sit amet, scelerisque vel ipsum. Phasellus vel diam efficitur, mattis nisi in, bibendum diam. Nulla fermentum facilisis blandit. Vestibulum eu lorem at nibh ornare faucibus id at nunc. Integer fringilla venenatis ante, id fermentum ligula interdum sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In hac habitasse platea dictumst. Vestibulum sed eros nec elit pellentesque tempor a iaculis libero. Maecenas iaculis nisl ac varius maximus. Proin ullamcorper placerat leo, suscipit mattis felis pellentesque ut. Mauris dictum felis eu tellus fringilla, nec consectetur quam sagittis. Pellentesque lorem erat, lacinia eu mollis non, ultricies in justo. Pellentesque pretium lacinia odio, non dignissim elit laoreet at. Nunc eu lectus eu lacus posuere sollicitudin. Ut lobortis cursus justo venenatis pellentesque. Fusce aliquet rhoncus tempus.', 2, '2019-07-11 02:21:57', 'preview1', NULL, NULL),
(10, 'Duis ornare justo non sem', 'Duis ornare justo non sem aliquam venenatis. Sed et nulla non dolor auctor efficitur. Fusce malesuada, quam non dignissim condimentum, sem nisl finibus elit, a congue sapien velit eget orci.', 'Duis ornare justo non sem aliquam venenatis. Sed et nulla non dolor auctor efficitur. Fusce malesuada, quam non dignissim condimentum, sem nisl finibus elit, a congue sapien velit eget orci. Etiam iaculis auctor quam vel pulvinar. Aenean laoreet lobortis nulla vitae dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pretium sapien in congue aliquet. Duis porttitor tempus lacus non accumsan. Maecenas convallis libero sed convallis lobortis. Aenean vel enim neque. Mauris suscipit at massa a gravida.  Cras vitae pharetra odio, eget lobortis orci. Mauris aliquam ex suscipit leo posuere varius. Curabitur ullamcorper enim libero, eget porttitor arcu interdum eu. Fusce justo libero, facilisis volutpat velit eget, euismod molestie erat. Donec vehicula et lacus sit amet efficitur. Maecenas vitae maximus justo, sed hendrerit nisi. Phasellus id libero ut dui posuere aliquet. In tempus enim id dolor tincidunt, at bibendum nisi tristique. Vestibulum condimentum, leo ut tincidunt luctus, nunc turpis iaculis velit, et efficitur mi urna sed dui. Duis rhoncus nisl quis finibus molestie. Maecenas in vehicula metus. Vestibulum mattis vitae risus eu ornare. Nunc non molestie ligula. Donec quis diam vulputate, lacinia libero vitae, vehicula sapien.', 2, '2019-07-11 02:22:27', 'preview1', NULL, NULL),
(11, 'Nullam vitae urna ultrices', 'Nullam vitae urna ultrices, aliquet arcu id, malesuada turpis. Nam non finibus turpis. Donec condimentum, velit ut ultrices tristique, velit nulla rutrum dui, sed aliquet elit orci eu turpis.', 'Nullam vitae urna ultrices, aliquet arcu id, malesuada turpis. Nam non finibus turpis. Donec condimentum, velit ut ultrices tristique, velit nulla rutrum dui, sed aliquet elit orci eu turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam vitae urna id magna dignissim consectetur. Donec sit amet tellus rhoncus, molestie turpis a, efficitur lorem. Nunc molestie ante eget consequat imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis tempus lorem in ligula scelerisque sodales. Proin auctor odio et ex finibus, nec auctor est tempor. Quisque dignissim, ante eu tincidunt venenatis, dui neque luctus justo, ac semper ligula odio ut tortor. Cras at luctus dui, vel rutrum mi. Vestibulum id feugiat nulla. Nullam commodo lectus sed velit molestie condimentum. Mauris consectetur odio ut euismod aliquet. Nullam condimentum odio vel ex facilisis vehicula ut vel risus.  Curabitur nibh nisl, maximus nec enim id, molestie congue tellus. Integer fermentum luctus nulla, vitae sodales dolor. Integer sed leo ut orci scelerisque placerat. Maecenas blandit magna ex, id efficitur purus imperdiet ac. Fusce feugiat massa vitae faucibus mattis. Etiam nec erat mi. Integer vitae mattis leo, venenatis fermentum quam. Quisque at quam quis lorem accumsan aliquam tincidunt ut purus. In a vestibulum erat, vel fermentum ex. Vivamus egestas pharetra risus ut tristique. Vestibulum at iaculis eros, a euismod turpis. Donec faucibus tellus ac ipsum vestibulum, ac hendrerit risus iaculis. Nunc vel gravida nunc. Morbi eleifend, lacus vel consequat mollis, ante risus molestie quam, eget pharetra nunc quam quis nibh. Aliquam erat volutpat. Curabitur a consectetur libero.', 2, '2019-07-11 02:22:54', 'preview1', NULL, NULL),
(12, 'Praesent vitae laoreet nisl', 'Praesent vitae laoreet nisl. Vivamus dapibus aliquet vulputate. Donec eu pharetra metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Praesent vitae laoreet nisl. Vivamus dapibus aliquet vulputate. Donec eu pharetra metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac ante sit amet neque efficitur cursus eu sed justo. Vivamus nec maximus arcu, et lobortis urna. Morbi pharetra elit id mauris hendrerit, ut tristique arcu cursus. Nulla gravida elementum elit, a fermentum erat pretium id. Morbi dictum viverra libero vitae sollicitudin. Mauris commodo scelerisque magna. Aliquam scelerisque semper justo vel dictum.  Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam ullamcorper velit a vulputate finibus. Mauris a gravida ligula. Maecenas tempor convallis viverra. Integer venenatis, lacus eu luctus luctus, metus ex mattis eros, et placerat nulla eros ac odio. Ut dui ipsum, blandit ac magna sit amet, rutrum fringilla purus. Nunc commodo elementum sagittis. Mauris pulvinar libero nec ligula iaculis, quis pretium urna imperdiet. Maecenas porta maximus dolor vitae cursus.', 2, '2019-07-11 02:25:09', 'preview1', NULL, NULL),
(13, 'Ut feugiat posuere dolor', 'Ut feugiat posuere dolor imperdiet vestibulum. Cras ullamcorper libero fermentum varius rutrum. In hac habitasse platea dictumst.', 'Ut feugiat posuere dolor imperdiet vestibulum. Cras ullamcorper libero fermentum varius rutrum. In hac habitasse platea dictumst. Donec ultricies, tellus in fringilla venenatis, elit urna sodales felis, ut egestas magna est sit amet felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent mi tortor, ultricies et diam non, imperdiet varius lorem. Vivamus vitae commodo magna, ut sollicitudin enim. Ut suscipit tellus velit, ac tristique quam mattis elementum. Nunc ut varius justo.  Aenean ut nulla risus. Proin quis imperdiet purus. Sed fringilla varius gravida. Cras consectetur nisl ut justo commodo egestas. Mauris luctus eget diam sed consectetur. Donec augue libero, elementum ac convallis nec, gravida nec leo. Fusce non elit ut magna varius feugiat vitae non neque. Pellentesque a purus molestie, auctor purus ut, porttitor velit. Aliquam viverra quam sit amet purus posuere varius ut et arcu. Donec varius tortor lacinia turpis interdum, vitae finibus odio interdum. Donec egestas placerat elit ac sodales. Cras tincidunt sem augue, in facilisis metus sagittis id.', 1, '2019-07-11 02:25:41', 'preview1', NULL, NULL),
(14, 'Aenean tempor nulla vitae', 'Aenean tempor nulla vitae tempor hendrerit. Pellentesque eu fringilla mi. Integer sit amet nulla at velit lobortis auctor eu vel augue. Nulla ac posuere dolor.', 'Aenean tempor nulla vitae tempor hendrerit. Pellentesque eu fringilla mi. Integer sit amet nulla at velit lobortis auctor eu vel augue. Nulla ac posuere dolor. Sed id felis ornare, blandit risus vitae, volutpat eros. Aenean molestie, purus non lobortis ultricies, orci neque elementum tellus, ac porta risus eros eget nisi. Vivamus vestibulum eros ac vestibulum egestas. Vivamus at urna quis magna aliquam congue non et lectus. Suspendisse eu tincidunt quam, non congue purus. Phasellus at ipsum sed ex volutpat tristique eu at purus. Aliquam hendrerit vestibulum urna in faucibus. Proin auctor sagittis ipsum, eu sodales mauris dignissim eu. Phasellus vitae efficitur mi.  Mauris sed lobortis diam. In mollis posuere viverra. Praesent lacinia, mauris non maximus egestas, risus dui finibus tortor, a imperdiet augue leo sed turpis. Suspendisse potenti. Sed odio nulla, gravida cursus tincidunt eu, laoreet sit amet erat. Integer quis massa metus. Ut posuere eget ligula in tempor. Sed lorem massa, efficitur et justo non, pellentesque ultricies tellus. Aliquam vitae tortor sit amet risus tempus hendrerit. Integer pulvinar egestas nisi. Sed mi mauris, sagittis tempus ligula in, mollis convallis mi. Sed vel rutrum sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.', 1, '2019-07-11 02:26:11', 'preview1', NULL, NULL),
(15, 'In semper elementum tempus', 'In semper elementum tempus. Sed gravida id justo quis congue. Integer lobortis, nunc a vehicula tristique, arcu tortor auctor arcu, sed mattis nisi risus non lectus.', 'In semper elementum tempus. Sed gravida id justo quis congue. Integer lobortis, nunc a vehicula tristique, arcu tortor auctor arcu, sed mattis nisi risus non lectus. Donec iaculis et justo et fermentum. Maecenas condimentum erat sit amet lorem blandit ullamcorper. Donec ornare vulputate auctor. Nam aliquet tincidunt ligula. Curabitur fermentum elementum leo quis egestas. In maximus ultricies justo, quis lacinia nisl rutrum eu.  Nunc lobortis nisi eget metus mollis accumsan. Cras tincidunt blandit ex. Vivamus mi diam, tristique sed venenatis at, imperdiet id felis. Nulla quis lorem lorem. Phasellus porta mollis lorem, porttitor condimentum nisi iaculis id. Nulla blandit nec augue in eleifend. Mauris tincidunt suscipit est, sit amet fringilla ex rutrum id. Maecenas dignissim nunc massa, at posuere turpis dignissim sit amet.  Aliquam sed eros id nisi sagittis ornare id non metus. Morbi luctus blandit neque et viverra. Fusce vitae turpis eu leo tempus blandit. Etiam pharetra rutrum varius. Aliquam convallis, diam at vulputate fringilla, tortor felis blandit mi, in accumsan odio erat in velit. Nulla consequat egestas aliquet. Suspendisse arcu urna, gravida nec condimentum at, mattis in eros. Praesent metus ex, mattis tempor orci tincidunt, tincidunt iaculis enim. Nulla tempus urna sit amet tincidunt interdum. Donec mollis eros ac tempor auctor.', 2, '2019-07-11 02:26:42', 'preview1', NULL, NULL),
(16, 'Aenean efficitur erat vitae', 'Aenean efficitur erat vitae dolor aliquet, quis fermentum justo pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Aenean efficitur erat vitae dolor aliquet, quis fermentum justo pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut interdum arcu lacus, at vestibulum orci dictum id. Morbi pulvinar quam in diam sodales pretium. Aliquam gravida, magna vitae facilisis cursus, magna libero aliquam tellus, quis sollicitudin nunc ante id nisl. Vestibulum vel turpis et justo interdum finibus. Donec eleifend tincidunt nibh ac congue. Morbi ac felis eros. Vivamus metus tortor, ultricies vitae mi vitae, tempus vestibulum nisl. Aliquam erat volutpat. Aliquam velit sapien, auctor eu rhoncus eu, fringilla et diam. Proin venenatis ligula venenatis ipsum pulvinar congue. Aenean hendrerit felis eu maximus elementum. Proin dui ipsum, rutrum a bibendum vitae, varius sit amet metus. Donec congue quis arcu sed scelerisque. Nunc sit amet gravida quam, quis tincidunt nunc.  Sed commodo laoreet blandit. Ut lacinia erat in ipsum rutrum mollis. Sed consectetur viverra erat at dictum. Donec ac ante non libero consectetur feugiat. Nulla ullamcorper, eros et eleifend hendrerit, velit odio ultricies sem, sed tincidunt lorem eros a purus. Praesent fringilla lorem eleifend nibh efficitur, quis placerat enim ultrices. Proin vel dictum justo, a laoreet odio.', 2, '2019-07-11 02:27:15', 'preview1', NULL, NULL),
(17, 'Aenean a massa eu tortor', 'Aenean a massa eu tortor volutpat molestie non ut mi. In hac habitasse platea dictumst. Suspendisse pretium fringilla ipsum, a pharetra lorem eleifend et.', 'Aenean a massa eu tortor volutpat molestie non ut mi. In hac habitasse platea dictumst. Suspendisse pretium fringilla ipsum, a pharetra lorem eleifend et. Phasellus a suscipit ipsum. Etiam eget rhoncus nibh. Cras consequat urna vel metus cursus porttitor. Ut ac sollicitudin tortor, ac porta massa. Integer at sagittis justo. Curabitur imperdiet orci non urna ullamcorper, non rhoncus purus finibus. Nullam nec diam in arcu maximus pharetra. Curabitur convallis turpis non aliquam condimentum. Donec vestibulum ex nisi, ut maximus mauris dignissim sit amet. Vivamus quis venenatis sem. Proin rutrum sed libero ac pretium.  Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin tristique velit id velit dapibus placerat. Quisque quis ullamcorper nisl, sit amet bibendum mauris. Nullam dapibus eget nibh ac tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus in velit quis nunc finibus tincidunt ut quis augue. Curabitur sagittis elementum lectus, id ullamcorper magna venenatis a. Vestibulum vehicula risus ante, a maximus neque accumsan vel. Donec at mauris eu libero lobortis dapibus non et felis. Phasellus placerat lacus justo, nec faucibus tellus imperdiet ac. Sed pellentesque laoreet ligula at placerat. Aliquam id facilisis lectus, eget commodo metus. Sed ullamcorper facilisis lacus, in euismod lacus pellentesque a. Ut sed suscipit odio.', 1, '2019-07-11 02:27:45', 'preview1', NULL, NULL),
(18, 'Suspendisse lacinia justo', 'Suspendisse lacinia justo at posuere volutpat. Maecenas consequat viverra metus, nec auctor libero vehicula at. Praesent sapien nisi, dapibus quis nisl et, vehicula tristique massa.', 'Suspendisse lacinia justo at posuere volutpat. Maecenas consequat viverra metus, nec auctor libero vehicula at. Praesent sapien nisi, dapibus quis nisl et, vehicula tristique massa. Aliquam id tempus orci. Fusce et quam eu magna malesuada imperdiet. Curabitur at eleifend nisi, et dictum libero. Proin facilisis est nec sodales sagittis. Nulla non vulputate risus, non accumsan est. Sed sodales neque faucibus blandit commodo. Pellentesque quis porttitor nunc, eget varius ipsum. Mauris vestibulum tempus efficitur. Ut pharetra lacus mattis, molestie orci vitae, mattis enim. Integer congue pellentesque consequat.  Sed in ante nec nisl euismod dignissim sed eget justo. Morbi sit amet posuere tortor. Nulla venenatis augue lacus, at scelerisque ipsum efficitur vitae. Cras at euismod diam. Aliquam scelerisque, sapien sed vulputate tempus, justo diam venenatis metus, tincidunt eleifend mauris ex at velit. Ut quis dictum massa, vel porttitor lectus. Maecenas ac nibh quis augue mollis faucibus. Curabitur elementum metus ac nisi tincidunt, ac commodo elit varius. Etiam finibus consequat ex at egestas. Nulla euismod quis turpis vitae dictum. Ut in ante vel felis volutpat aliquam sed ut elit. Sed quis fermentum elit. Phasellus consequat enim porta turpis suscipit, a ornare nulla blandit. Sed feugiat varius turpis, eu mattis lorem. Sed tincidunt metus ut erat luctus, ac pretium erat pharetra.', 2, '2019-07-11 02:28:17', 'preview1', NULL, NULL),
(19, 'Sed vestibulum', 'Sed vestibulum, ligula et mattis posuere, purus nulla dignissim sem, nec dapibus ligula ipsum a ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.', 'Sed vestibulum, ligula et mattis posuere, purus nulla dignissim sem, nec dapibus ligula ipsum a ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut quis lorem ac urna congue porta. Cras id sem eleifend, aliquet nibh vel, vestibulum augue. Morbi vulputate vel nunc quis imperdiet. Donec cursus tellus magna, vitae suscipit risus placerat ac. Integer posuere sed orci in rhoncus. Duis in eros ultricies massa congue aliquam eu vitae diam. Curabitur dictum molestie risus quis interdum. Nunc convallis dui et erat sodales, quis blandit lacus vulputate. Aenean faucibus felis eget risus semper, et malesuada nunc congue. Integer ultricies dolor varius erat venenatis vestibulum. Quisque mattis diam sed enim dignissim, sollicitudin imperdiet lectus gravida. Pellentesque quis sem nunc. Curabitur accumsan, dui nec congue placerat, augue libero aliquam erat, id tincidunt mi arcu vitae leo. Nunc tempor ultricies imperdiet.  Morbi purus mauris, rhoncus quis nisl nec, consectetur vehicula massa. Sed lectus nisi, mattis et risus nec, varius iaculis risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent malesuada non nibh id luctus. Curabitur ut ipsum sit amet elit viverra condimentum vel non ligula. Nullam bibendum sagittis lectus vel hendrerit. Aliquam ante risus, ullamcorper at posuere a, egestas non mi.', 1, '2019-07-11 02:28:43', 'preview1', NULL, NULL),
(20, 'Vestibulum feugiat magna', 'Vestibulum feugiat magna non dignissim vestibulum. Proin magna ex, eleifend quis vulputate sit amet, euismod in leo. Ut quis metus mauris.', 'Vestibulum feugiat magna non dignissim vestibulum. Proin magna ex, eleifend quis vulputate sit amet, euismod in leo. Ut quis metus mauris. Proin sodales tempor eleifend. Cras tempor augue eu lorem ultrices interdum. Phasellus id enim nec est elementum tincidunt. Vestibulum consectetur velit vel mauris auctor malesuada. Ut sollicitudin purus id eros maximus luctus. Duis commodo lacinia lacus, at facilisis lorem sollicitudin eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean nisl purus, porttitor quis nisi vitae, dictum auctor leo. Sed finibus neque at ligula lobortis, nec egestas lectus molestie. Curabitur convallis, erat nec semper eleifend, nisl leo tincidunt nisl, eget bibendum lacus quam id odio. Nulla vel lectus elementum, egestas leo vitae, pharetra nunc. Aenean aliquet lacus at pulvinar blandit.  Nulla tincidunt quam a eleifend lacinia. Aliquam vitae posuere justo. Phasellus sit amet mi nisi. Nam feugiat viverra massa, in sagittis sapien luctus eu. Morbi feugiat lectus eu varius tincidunt. Vestibulum vitae urna vitae tellus pulvinar maximus sit amet ut ligula. Donec luctus eros quam, et suscipit sapien tempus vel. Nullam vitae quam vel tortor ultricies egestas eu non dolor. Aliquam dapibus risus eu quam congue, in tempor odio interdum.', 2, '2019-07-11 02:29:16', 'preview1', NULL, NULL),
(21, 'Duis pulvinar non', 'Duis pulvinar non felis nec rhoncus. Cras eu maximus dolor. Fusce malesuada tempor tempor. Duis interdum consectetur consectetur.', 'Duis pulvinar non felis nec rhoncus. Cras eu maximus dolor. Fusce malesuada tempor tempor. Duis interdum consectetur consectetur. Pellentesque risus velit, congue quis ultrices quis, placerat sed urna. Nulla facilisi. In erat mauris, ultricies in tortor at, porttitor interdum quam. Sed in dignissim nisl, sit amet accumsan sem. Fusce non elit in nunc pharetra laoreet vel in odio. Ut ultrices ex et sem auctor lobortis. Donec sit amet gravida metus, non consectetur sem. Donec vulputate eros sit amet nunc tempor, non tincidunt nisl condimentum. Praesent cursus turpis et urna ornare dapibus. Quisque tellus libero, cursus sed commodo eget, iaculis et massa.  Nunc tortor nisl, vulputate a rutrum at, porttitor nec ipsum. Maecenas nisl sapien, tristique at posuere vel, tristique eu nulla. Phasellus imperdiet erat a quam viverra, ac commodo tellus lobortis. Praesent id viverra diam, facilisis vehicula est. Nulla convallis ex et est sagittis fringilla. Nam sagittis et leo sed fringilla. Fusce ullamcorper, mi commodo hendrerit cursus, ipsum sem interdum quam, et consectetur ipsum massa ut velit.  Fusce mattis iaculis ipsum. Vivamus at metus at ex ornare blandit. Nulla facilisi. In a magna at odio dictum tincidunt. Ut tristique mi nisl. Pellentesque eget augue vitae diam fermentum consectetur. Morbi viverra sagittis rutrum. Sed tellus sapien, interdum id tempus nec, pharetra at velit.', 1, '2019-07-11 02:29:39', 'preview1', NULL, NULL),
(22, 'Vivamus vel lorem efficitur', 'Vivamus vel lorem efficitur, accumsan mi eleifend, imperdiet velit. Curabitur euismod est a sodales ultrices. Quisque dictum arcu nec nunc finibus, sodales accumsan leo maximus.', 'Vivamus vel lorem efficitur, accumsan mi eleifend, imperdiet velit. Curabitur euismod est a sodales ultrices. Quisque dictum arcu nec nunc finibus, sodales accumsan leo maximus. Morbi ut dapibus turpis. Curabitur nec felis turpis. Fusce maximus tortor a mollis iaculis. Morbi erat leo, dignissim a mattis non, euismod vitae tellus. Vestibulum nec leo tortor. Vivamus vehicula diam nec sollicitudin consectetur. Suspendisse potenti. Sed mollis et ex non molestie. Integer eu tortor pellentesque, viverra diam at, dapibus eros. Pellentesque tristique auctor libero, eget ultricies odio placerat in. Ut pellentesque odio eget erat tincidunt, in consectetur tortor mollis. In ac ornare ligula.  Donec tortor nisi, tincidunt id hendrerit vitae, feugiat a nulla. Suspendisse eu lacus consectetur, commodo est quis, accumsan justo. Nulla augue nunc, mattis egestas nibh eu, rutrum tincidunt neque. In malesuada convallis urna in fermentum. Integer vel mi pretium, ultrices nisi eget, interdum felis. Pellentesque at metus dui. Cras imperdiet mauris sapien. Integer lacinia dictum leo vitae auctor. Donec blandit felis non dignissim volutpat.  Cras ullamcorper tempus rhoncus. Nam ex urna, suscipit a auctor eget, hendrerit sit amet justo. Praesent ac arcu sodales, facilisis tortor sit amet, euismod massa. Praesent ac imperdiet eros. Morbi vitae arcu nulla. Donec blandit est non lacus bibendum mattis eget et dolor. Nunc et tincidunt libero. Maecenas dapibus augue eleifend enim commodo, a cursus turpis facilisis. Nam in pulvinar arcu, vitae tristique ligula. Praesent in varius orci, vel porta lacus.', 2, '2019-07-11 02:30:08', 'preview1', NULL, NULL),
(23, 'Fusce mauris libero', 'Fusce mauris libero, ultricies in laoreet et, rutrum in nulla. Donec elementum tincidunt feugiat. Morbi sodales id lectus sit amet accumsan.', 'Fusce mauris libero, ultricies in laoreet et, rutrum in nulla. Donec elementum tincidunt feugiat. Morbi sodales id lectus sit amet accumsan. Morbi erat urna, sagittis ut sem ut, bibendum imperdiet leo. Nunc nec quam est. Vestibulum leo est, rhoncus eu sapien vel, sagittis maximus lectus. Morbi et placerat est. Phasellus magna mauris, malesuada sed dolor at, porttitor mattis neque. In blandit arcu mollis purus dignissim scelerisque.  Ut suscipit diam quis consequat consectetur. Aenean ut venenatis libero. Aliquam ultrices, lorem at consectetur sollicitudin, nisl nunc condimentum sapien, sed vulputate tortor dui sit amet quam. Sed aliquam elit et lectus semper, ut semper libero vulputate. Nulla facilisi. Nam libero tellus, dignissim vel ultrices interdum, efficitur eget arcu. Nulla facilisi. Mauris tristique purus enim, sed imperdiet mi scelerisque id. Etiam eu quam vel quam elementum sodales vel quis purus. Vestibulum in libero sed libero iaculis accumsan. Nam commodo est ligula, rutrum congue lacus placerat in. Donec eu efficitur urna. Sed rutrum feugiat ligula eu imperdiet.', 2, '2019-07-11 02:30:47', 'preview1', NULL, NULL),
(24, 'Mauris quis imperdiet', 'Mauris quis imperdiet ipsum. Aliquam faucibus venenatis felis, quis placerat justo rhoncus eu. Maecenas eu tortor enim.', 'Mauris quis imperdiet ipsum. Aliquam faucibus venenatis felis, quis placerat justo rhoncus eu. Maecenas eu tortor enim. Mauris consequat, nulla ut laoreet congue, lacus ex laoreet ligula, quis pretium enim nibh et odio. Ut ac aliquam nisi. Maecenas vitae mi vulputate, suscipit lorem eu, suscipit turpis. Mauris pulvinar, ante vel dapibus eleifend, sem est semper nulla, et auctor nulla est nec dolor. Pellentesque eu dui luctus, euismod lorem in, luctus massa. Cras convallis aliquam congue. Sed non tellus maximus, auctor nibh eget, eleifend orci. Donec interdum quis sem nec posuere. Maecenas malesuada orci vitae neque volutpat, ut sodales nisi auctor. Ut sit amet est sit amet urna ullamcorper venenatis vel ut sem. Pellentesque commodo metus porta quam porttitor, eu consectetur nunc accumsan. Nam rutrum mattis lacus a porttitor.  Vivamus convallis, sapien quis cursus semper, nisi justo consectetur augue, non ullamcorper urna eros nec quam. Integer eget velit urna. Integer mollis enim orci, ac dapibus erat interdum hendrerit. Nam a ultricies augue, vestibulum tempor diam. Pellentesque maximus felis eu ex rhoncus rhoncus. Nullam in nulla nec libero posuere lobortis. Mauris eget quam ligula. Fusce luctus metus lorem, in consequat orci cursus ut. Duis egestas pretium mi nec convallis. Suspendisse nunc felis, sollicitudin vitae erat quis, vestibulum viverra justo. Mauris faucibus dui eu tellus bibendum commodo. Integer est augue, accumsan gravida leo eget, dapibus tincidunt massa. Praesent non varius ex, a pretium justo.', 2, '2019-07-11 02:31:10', 'preview1', NULL, NULL),
(25, 'Sed dapibus feugiat', 'Sed dapibus feugiat nisi vitae fermentum. In hac habitasse platea dictumst. Fusce nec dui sed quam imperdiet viverra a sed lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Sed dapibus feugiat nisi vitae fermentum. In hac habitasse platea dictumst. Fusce nec dui sed quam imperdiet viverra a sed lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus pharetra lectus eget nisl sodales blandit et quis est. Nam gravida consectetur ante, eget sollicitudin est semper non. Nullam lacinia dolor vitae nisl varius, tempor luctus elit ultricies. Sed porttitor lorem et elit laoreet auctor. Morbi ut tellus a tellus volutpat tristique eu sed augue. Pellentesque dignissim, felis et lobortis tempor, ipsum metus auctor nibh, a dignissim turpis turpis nec metus. Nam in eros sit amet ante dignissim varius sed vel orci. Nam eu sapien nisi. Nullam consectetur augue ut velit dictum, et pulvinar nisl commodo.  Mauris ultrices enim a dapibus ornare. Integer fermentum ipsum ut eros elementum, id auctor neque malesuada. Mauris vel enim bibendum, blandit magna quis, porta felis. Etiam eleifend sem vitae mi commodo sagittis. Aenean tincidunt metus quis faucibus ultricies. Fusce lorem urna, consectetur vel leo eget, luctus faucibus libero. Ut posuere urna non egestas pharetra. Aenean ultrices euismod bibendum. Nullam cursus efficitur laoreet. Aliquam condimentum rutrum quam id lobortis. Integer felis nunc, pretium suscipit posuere at, cursus quis dui.  Praesent mauris lacus, luctus consectetur elit at, dictum viverra orci. Phasellus et mattis erat. Nam molestie dolor lectus, sit amet sagittis mauris luctus id. Quisque faucibus sagittis elit vel mollis. Fusce ut faucibus ipsum, sit amet laoreet lacus. In sit amet ex ipsum. Aenean vitae ante nisi. Morbi scelerisque eros metus, ac pretium risus condimentum ac.', 1, '2019-07-11 02:31:35', 'preview1', NULL, NULL),
(26, 'Sed vehicula consequat', 'Sed vehicula consequat felis, vitae finibus nulla commodo iaculis. Nullam tincidunt arcu vitae justo eleifend, eget viverra diam ultrices. Donec ut vehicula ipsum.', 'Sed vehicula consequat felis, vitae finibus nulla commodo iaculis. Nullam tincidunt arcu vitae justo eleifend, eget viverra diam ultrices. Donec ut vehicula ipsum. Nam laoreet ut nulla vel hendrerit. Maecenas vitae quam venenatis, porta risus quis, vulputate orci. Etiam et lacinia mi. Nunc eget sagittis nibh. Vestibulum id vulputate purus.  Praesent id blandit metus, in mollis dui. Nam nisl elit, tristique a mauris at, malesuada hendrerit enim. Suspendisse vel porta nisi. Integer ut metus sit amet tellus efficitur sodales. Duis sollicitudin nec magna id cursus. In mi enim, varius ac cursus vitae, laoreet ut elit. Maecenas quis congue dui, at egestas neque. Vestibulum placerat ex in leo posuere gravida. Donec hendrerit turpis nec justo pulvinar interdum. Maecenas urna sem, tristique nec ante id, dignissim gravida purus. Sed id porttitor turpis.  Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec scelerisque tempor dolor id rhoncus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt est orci, sed facilisis tortor lacinia et. Proin condimentum porta nisl, mollis laoreet nulla pharetra vel. Nunc in laoreet neque, sit amet tempor quam. Proin sit amet odio at lectus pellentesque tempus ut ac nisi. Donec quis efficitur diam. Morbi ornare in augue a gravida. Vestibulum arcu lorem, sodales nec congue in, pulvinar at risus.', 1, '2019-07-11 02:32:07', 'preview1', NULL, NULL),
(27, 'In hac habitasse platea', 'In hac habitasse platea dictumst. Sed luctus magna nec bibendum dapibus. Phasellus rhoncus gravida lacus, quis aliquet quam consectetur vitae.', 'In hac habitasse platea dictumst. Sed luctus magna nec bibendum dapibus. Phasellus rhoncus gravida lacus, quis aliquet quam consectetur vitae. Fusce aliquet lacinia lorem, eu egestas orci viverra sit amet. Sed mollis laoreet arcu, eu suscipit leo fermentum finibus. Phasellus maximus iaculis felis quis posuere. In ut rutrum ligula.  Etiam eu tortor fermentum, efficitur velit quis, ultricies risus. Maecenas faucibus rhoncus lectus. Maecenas dignissim placerat eleifend. Etiam vestibulum nulla sed eleifend hendrerit. Sed sed malesuada nulla. Morbi feugiat eget magna eget convallis. Praesent eget condimentum metus. Nulla nec vehicula velit. Aliquam tortor leo, pulvinar a vehicula at, vulputate sit amet tellus. Morbi iaculis justo non massa pulvinar facilisis. Proin consectetur augue vitae eros sagittis, id ullamcorper felis euismod. Phasellus iaculis vitae dolor at lobortis. Suspendisse accumsan elit vitae porttitor sollicitudin. Quisque tincidunt purus nec orci feugiat consectetur. Morbi ut nibh at augue lobortis interdum non imperdiet mi.  Aliquam vestibulum tellus non hendrerit ultrices. Suspendisse felis lacus, interdum a consequat tincidunt, sollicitudin finibus leo. Mauris diam metus, laoreet at sollicitudin eget, consectetur vitae nulla. Cras nec nisl id dui finibus dapibus at vel tellus. Nullam tincidunt est quis sollicitudin accumsan. Sed vehicula eros sed gravida egestas. In feugiat magna eu tortor eleifend, et faucibus velit molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', 1, '2019-07-11 02:32:38', 'preview1', NULL, NULL),
(28, 'Aenean accumsan eget ipsum', 'Aenean accumsan eget ipsum vitae egestas. Nulla aliquam fringilla erat at aliquam.', 'Aenean accumsan eget ipsum vitae egestas. Nulla aliquam fringilla erat at aliquam. Maecenas non ex ac magna suscipit ornare. Nulla in urna elementum, gravida eros a, ultrices quam. Suspendisse potenti. Nam aliquet gravida metus, at aliquet arcu placerat sit amet. In hac habitasse platea dictumst. Vivamus pellentesque aliquam tincidunt.  Duis sit amet ipsum ac quam congue porttitor. Sed eget diam id nibh placerat euismod. Sed ornare sem ac risus gravida varius. Cras quis quam a enim hendrerit facilisis vitae in mi. Donec ac lacinia nulla. Donec a nisl at nunc rutrum pharetra. Proin sed nisl ut nisi aliquam pulvinar. In sit amet lobortis nunc. Nulla in congue dolor. Sed at tincidunt nunc, ut mattis augue. Nunc hendrerit enim vitae purus volutpat imperdiet. Nunc aliquet scelerisque est, quis maximus libero. Interdum et malesuada fames ac ante ipsum primis in faucibus. In vehicula augue a est egestas placerat. Vestibulum lobortis sagittis risus.  Integer tristique metus vel diam consectetur vulputate. Donec sed ante lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vitae lacus sed velit posuere placerat rutrum eget neque. Pellentesque et erat nec enim laoreet vestibulum quis at dolor. Aliquam eu bibendum lectus. Pellentesque sollicitudin dui sodales leo vulputate, in auctor mi congue. Suspendisse volutpat mauris nec est auctor faucibus. Aliquam nisi neque, eleifend vitae porta a, varius nec magna. Proin venenatis arcu quis consequat blandit. Nunc ac interdum mauris.', 1, '2019-07-11 02:33:01', 'preview1', NULL, NULL),
(29, 'Suspendisse potenti', 'Suspendisse potenti. Praesent enim libero, pretium id justo eget, tempor tincidunt sapien. Pellentesque tincidunt tempus justo a rutrum.', 'Suspendisse potenti. Praesent enim libero, pretium id justo eget, tempor tincidunt sapien. Pellentesque tincidunt tempus justo a rutrum. Sed id orci vitae tellus pulvinar auctor. Sed feugiat accumsan elit a placerat. Duis imperdiet et elit sed pulvinar. Vestibulum et ex lectus. Sed sodales neque mattis leo vulputate sollicitudin. Integer ullamcorper placerat rutrum. Morbi molestie lobortis sodales. Sed nec libero neque. Aliquam elementum condimentum nisl vel finibus. Donec a massa laoreet, pulvinar ipsum et, consequat nunc. Integer eget sagittis orci.  Maecenas pulvinar purus ac tortor venenatis, et venenatis odio pharetra. Cras interdum nunc dolor, nec tincidunt elit dictum a. Duis vitae diam eu ex fermentum pharetra. Aliquam nibh nisi, porttitor nec ante a, vulputate suscipit metus. Praesent ultrices quam orci, nec dictum risus iaculis ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras mollis libero in egestas blandit. Aenean sit amet mi bibendum neque pretium dictum et ut erat. Phasellus accumsan pharetra urna eu bibendum. Donec ac tempor velit. Duis ultricies tortor ipsum, at dictum tortor sagittis vel. Nulla blandit, odio nec molestie elementum, orci risus pulvinar eros, a vehicula urna felis eu nisi. Nunc consequat metus at eleifend congue. Donec eget ante ac ligula pellentesque eleifend. Nulla porta metus ut mauris pharetra, a eleifend sem gravida. Sed quis orci porttitor, tristique lorem eget, iaculis sapien.', 2, '2019-07-11 02:33:22', 'preview1', NULL, NULL),
(30, 'Cras at est faucibus', 'Cras at est faucibus diam pretium convallis non eget tortor. Vestibulum a placerat odio. Integer at commodo quam. Maecenas eleifend purus in cursus egestas.', 'Cras at est faucibus diam pretium convallis non eget tortor. Vestibulum a placerat odio. Integer at commodo quam. Maecenas eleifend purus in cursus egestas. Ut maximus sit amet sapien at dignissim. Mauris interdum tincidunt eros, vel facilisis nisl cursus vitae. Nam semper a odio eu ultrices. Quisque lobortis leo at congue laoreet. Mauris ac posuere lectus, sit amet egestas arcu. Phasellus ullamcorper vestibulum sapien nec tincidunt. Vivamus suscipit aliquam cursus. Donec non justo eget urna bibendum commodo nec sed elit. Sed facilisis risus purus, quis rhoncus lorem iaculis a.  Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam dapibus pellentesque euismod. Pellentesque elementum varius porta. Duis ut faucibus est. Integer in dolor vel nulla tincidunt rutrum ut quis sem. Duis luctus sed erat vel cursus. Nullam vitae ipsum rutrum, tincidunt diam tempor, dictum est.  Sed cursus magna vel ex cursus pellentesque. Curabitur blandit purus orci, sed imperdiet elit dapibus at. Nam sagittis ligula tellus. Pellentesque suscipit venenatis maximus. Cras eu lectus id est consectetur pulvinar. In finibus ut lectus vel tempus. Nam ultricies cursus orci, vulputate viverra nunc semper eu. Proin cursus dignissim arcu, sit amet facilisis dui ullamcorper id. Mauris rhoncus laoreet suscipit. Nunc et fringilla odio, nec aliquam arcu.', 2, '2019-07-11 02:33:43', 'preview1', NULL, NULL);
INSERT INTO `articles` (`id`, `title`, `desc`, `content`, `news_users_id`, `date_created`, `photo`, `created_at`, `updated_at`) VALUES
(31, 'Mauris dapibus a tortor', 'Mauris dapibus a tortor vel venenatis. Praesent ornare tortor arcu. Etiam viverra felis molestie, aliquet sapien in, fringilla magna. Vestibulum vitae augue magna.', 'Mauris dapibus a tortor vel venenatis. Praesent ornare tortor arcu. Etiam viverra felis molestie, aliquet sapien in, fringilla magna. Vestibulum vitae augue magna. Vivamus ornare suscipit felis ut vulputate. Donec eget scelerisque ex. Etiam rhoncus, nisi vel efficitur lacinia, sem nulla cursus elit, id dapibus odio purus sed enim. Etiam viverra elit lectus, nec congue orci sodales ut. Curabitur a massa quam. Proin fringilla dui eget bibendum porttitor. Integer vehicula neque vitae mi dictum vulputate. Ut ac elementum ex, ac dictum diam. In rutrum, felis a dignissim finibus, nibh velit vehicula sapien, nec sagittis ipsum ipsum in diam.  Vestibulum eu elit non nibh rhoncus maximus. Nunc auctor urna vel aliquet commodo. Nunc eget magna ut sapien pulvinar consequat et et magna. Nulla facilisi. Donec ante sem, ornare ac porta in, aliquam id arcu. Fusce eget libero lacus. Vivamus interdum sapien in condimentum posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique lobortis lacinia. Integer mattis tortor vitae tempus sagittis. Curabitur semper consequat diam, in vulputate mauris fringilla quis. Phasellus dapibus facilisis diam, quis aliquet felis commodo ut. Praesent mollis dui massa, quis faucibus nisl placerat eu. Donec nunc augue, porttitor eu cursus sit amet, aliquet eu sapien. In hac habitasse platea dictumst. Ut porta erat massa, eget lobortis enim maximus fringilla.', 2, '2019-07-11 02:34:08', 'preview1', NULL, NULL),
(32, 'Curabitur orci nisi', 'Curabitur orci nisi, elementum nec ipsum a, efficitur feugiat odio. Suspendisse facilisis scelerisque auctor. Sed dignissim quis ante et aliquam.', 'Curabitur orci nisi, elementum nec ipsum a, efficitur feugiat odio. Suspendisse facilisis scelerisque auctor. Sed dignissim quis ante et aliquam. Cras lobortis suscipit felis, vel varius sem pellentesque ac. Nullam nec convallis erat. Donec interdum, nisl vel molestie suscipit, purus leo blandit eros, eget congue enim nibh vitae tellus. Ut porta nibh vel diam volutpat, sed fringilla enim pretium. Phasellus ullamcorper aliquam nisi, vel fermentum justo molestie in. Pellentesque euismod tellus in lacus dignissim, in facilisis neque placerat. Phasellus convallis, justo id vulputate ullamcorper, eros justo pulvinar mauris, ac placerat neque turpis at metus. Donec eget ante sit amet tortor lacinia viverra.  Quisque dignissim justo vitae metus pretium scelerisque. Aenean vitae turpis auctor, congue arcu auctor, scelerisque odio. Pellentesque feugiat mi in velit vestibulum, vel consequat libero elementum. Pellentesque quis sodales arcu, a volutpat diam. Donec blandit feugiat ex, vitae aliquet nisi condimentum ac. Sed quis porta nunc. Praesent efficitur metus vel turpis venenatis, sit amet imperdiet enim tristique. Integer porttitor interdum feugiat.  Vestibulum finibus bibendum congue. Nam vel accumsan ipsum. Quisque porta eu tortor a tincidunt. Proin facilisis, justo laoreet pharetra ornare, augue neque egestas ante, in scelerisque nisi nisi et ex. Etiam id augue nec diam fringilla efficitur. Quisque facilisis eros orci, a luctus risus bibendum ac. Morbi a convallis erat. Proin est eros, consectetur a dictum ut, mollis pretium augue. Fusce non molestie ipsum, vel pulvinar tortor.', 2, '2019-07-11 02:34:39', 'preview1', NULL, NULL);

-- --------------------------------------------------------

--
-- Структура таблицы `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Структура таблицы `news_users`
--

CREATE TABLE `news_users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `first_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `middle_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `birth_date` date NOT NULL,
  `occupation` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `photo` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Дамп данных таблицы `news_users`
--

INSERT INTO `news_users` (`id`, `email`, `username`, `password`, `first_name`, `last_name`, `middle_name`, `birth_date`, `occupation`, `photo`, `created_at`, `updated_at`) VALUES
(1, 'nicole96@example.com', 'nicole96', 'iamnicole', 'Nicole', 'Pearson', NULL, '1996-08-26', 'Web Developer', 'profile1.png', NULL, NULL),
(2, 'andrew98@example.com', 'andrew98', 'iamandrew', 'Andrew', 'Hawkins', 'Johnson', '1998-09-12', 'UI Designer', 'profile2.jpg', NULL, NULL),
(7, 'vasya99@example.com', 'vasiliy99', 'iamvasya', 'Vasiliy', 'Ivanov', 'Petrovich', '1999-04-15', 'Software Engineer', 'profile1562832929.jpg', NULL, NULL);

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `articles_title_unique` (`title`),
  ADD KEY `articles_news_users_id_foreign` (`news_users_id`);

--
-- Индексы таблицы `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Индексы таблицы `news_users`
--
ALTER TABLE `news_users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `news_users_email_unique` (`email`),
  ADD UNIQUE KEY `news_users_username_unique` (`username`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `articles`
--
ALTER TABLE `articles`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;

--
-- AUTO_INCREMENT для таблицы `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT для таблицы `news_users`
--
ALTER TABLE `news_users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- Ограничения внешнего ключа сохраненных таблиц
--

--
-- Ограничения внешнего ключа таблицы `articles`
--
ALTER TABLE `articles`
  ADD CONSTRAINT `articles_news_users_id_foreign` FOREIGN KEY (`news_users_id`) REFERENCES `news_users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
